# setup.ps1 - 视觉桥多模型配置向导
# =============================================================
# 在本脚本同目录生成/更新 .env 配置文件。
#
# 用法（通过 setup.bat，或直接执行）：
#   powershell -ExecutionPolicy Bypass -File setup.ps1            交互式向导（推荐）
#   powershell -ExecutionPolicy Bypass -File setup.ps1 -Status    查看配置 + 测试连通
#   powershell -ExecutionPolicy Bypass -File setup.ps1 -RemoveKey 删除 .env
#   powershell -ExecutionPolicy Bypass -File setup.ps1 -SetKey <key> 向后兼容：直接设智谱 key
# =============================================================

param(
    [string]$SetKey,
    [switch]$RemoveKey,
    [switch]$Status
)

$ErrorActionPreference = 'Stop'
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$envFile = Join-Path $PSScriptRoot '.env'

# --- 加载服务商注册表 ---
. (Join-Path $PSScriptRoot 'providers.ps1')

# --- 工具函数 -------------------------------------------------
function Read-DotEnv {
    $map = @{}
    if (Test-Path -LiteralPath $envFile) {
        foreach ($line in Get-Content -LiteralPath $envFile -Encoding UTF8) {
            $line = $line.Trim()
            if (-not $line -or $line.StartsWith('#') -or $line -notmatch '=') { continue }
            $k = $line.Substring(0, $line.IndexOf('=')).Trim()
            $v = $line.Substring($line.IndexOf('=') + 1).Trim().Trim('"', "'")
            $map[$k] = $v
        }
    }
    return $map
}

function Get-EnvValue([string]$Name) {
    $v = [Environment]::GetEnvironmentVariable($Name, 'Process')
    if (-not $v) { $v = [Environment]::GetEnvironmentVariable($Name, 'User') }
    if (-not $v) { $v = [Environment]::GetEnvironmentVariable($Name, 'Machine') }
    return $v
}

# 写 .env。注释用 ASCII 英文，避免其他工具解析 .env 时乱码。
function Write-DotEnv([hashtable]$Map) {
    $lines = @(
        '# Vision Bridge configuration',
        '# Generated by setup.ps1. Do not commit this file.',
        '# Keys: VISION_PROVIDER, VISION_API_KEY, VISION_MODEL, VISION_BASE_URL',
        '# GLM_API_KEY is a backward-compatible alias when using glm.',
        ''
    )
    foreach ($k in $Map.Keys) { $lines += "$k=$($Map[$k])" }
    $lines += ''
    [IO.File]::WriteAllLines($envFile, $lines, [System.Text.UTF8Encoding]::new($false))
}

function Get-Config {
    $map = Read-DotEnv
    $provider = $map['VISION_PROVIDER']
    $apiKey   = $map['VISION_API_KEY']
    $model    = $map['VISION_MODEL']
    $baseUrl  = $map['VISION_BASE_URL']

    # 向后兼容：旧的 GLM_API_KEY
    if (-not $apiKey) { $apiKey = $map['GLM_API_KEY'] }
    if (-not $apiKey) { $apiKey = Get-EnvValue 'GLM_API_KEY' }
    if (-not $provider) { $provider = if ($apiKey) { 'glm' } else { '' } }

    if ($provider -and $VisionProviders.Contains($provider)) {
        if (-not $baseUrl) { $baseUrl = $VisionProviders[$provider].BaseUrl }
        if (-not $model)   { $model = $VisionProviders[$provider].Models[0] }
    }
    return @{ provider = $provider; apiKey = $apiKey; model = $model; baseUrl = $baseUrl; raw = $map }
}

function Test-Endpoint([string]$BaseUrl, [string]$ApiKey, [string]$Model) {
    try {
        if (-not $Model) { $Model = 'glm-4v-flash' }
        $body = @{
            model    = $Model
            messages = @(@{ role = 'user'; content = 'hi' })
        } | ConvertTo-Json -Depth 6
        $bodyBytes = [System.Text.Encoding]::UTF8.GetBytes($body)
        $uri = $BaseUrl.TrimEnd('/') + '/chat/completions'
        $r = Invoke-RestMethod -Uri $uri -Method Post -TimeoutSec 20 `
            -Headers @{ Authorization = "Bearer $ApiKey" } `
            -ContentType 'application/json; charset=utf-8' -Body $bodyBytes
        return 'OK'
    } catch {
        $status = 0
        if ($_.Exception.Response) { try { $status = [int]$_.Exception.Response.StatusCode } catch { } }
        return "FAIL($status) $($_.Exception.Message)"
    }
}

function Save-FromWizard {
    # ---- 第 0 步：显示当前配置 ----
    $cur = Get-Config
    if ($cur.provider) {
        Write-Host ""
        Write-Host ("当前配置：服务商 {0}，模型 {1}" -f $cur.provider, $cur.model) -ForegroundColor Gray
        Write-Host "重新配置会覆盖以下设置。" -ForegroundColor Gray
    } else {
        Write-Host ""
        Write-Host "尚未配置。" -ForegroundColor Gray
    }

    # ---- 第 1 步：选择服务商 ----
    Write-Host ""
    Write-Host "======== 视觉桥 - 多模型配置向导 ========" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "请选择视觉模型服务商：" -ForegroundColor Yellow
    $i = 0
    $ids = @()
    foreach ($id in $VisionProviders.Keys) {
        $i++
        $ids += $id
        Write-Host ("  {0}. {1}  [{2}]" -f $i, $VisionProviders[$id].Name, $id)
    }
    $sel = Read-Host "请输入编号 (1-$($ids.Count)，回车默认 1)"
    if ([string]::IsNullOrWhiteSpace($sel)) { $sel = '1' }
    $idx = 0
    if (-not [int]::TryParse($sel, [ref]$idx) -or $idx -lt 1 -or $idx -gt $ids.Count) {
        Write-Host "输入无效，使用 1（智谱 GLM）。" -ForegroundColor Yellow
        $idx = 1
    }
    $provider = $ids[$idx - 1]
    $p = $VisionProviders[$provider]
    Write-Host ""
    Write-Host ("已选择：{0}" -f $p.Name) -ForegroundColor Green

    # ---- 第 2 步：选择模型 ----
    $model = ''
    if ($p.Models.Count -gt 0) {
        Write-Host ""
        Write-Host "请选择模型：" -ForegroundColor Yellow
        $mi = 0
        foreach ($m in $p.Models) {
            $mi++
            Write-Host ("  {0}. {1}" -f $mi, $m)
        }
        $msel = Read-Host "请输入编号 (1-$($p.Models.Count)，回车默认 1)"
        if ([string]::IsNullOrWhiteSpace($msel)) { $msel = '1' }
        $mnum = 0
        if ([int]::TryParse($msel, [ref]$mnum) -and $mnum -ge 1 -and $mnum -le $p.Models.Count) {
            $model = $p.Models[$mnum - 1]
        } else {
            $model = $p.Models[0]
        }
    }

    # ---- 第 3 步：接口地址与模型（自定义服务商） ----
    $baseUrl = $p.BaseUrl
    if ($provider -eq 'custom') {
        $baseUrl = Read-Host "请输入接口地址 (Base URL，例如 https://api.example.com/v1)"
        if (-not $baseUrl) {
            Write-Host "自定义服务商必须填接口地址。" -ForegroundColor Red
            exit 1
        }
        $model = Read-Host "请输入模型名称（例如 gpt-4o，回车默认 gpt-4o）"
        if (-not $model) { $model = 'gpt-4o' }
    }

    # ---- 第 4 步：填写 API Key ----
    $apiKey = ''
    if ($p.NeedsKey) {
        $apiKey = Read-Host "请输入 API Key"
        if (-not $apiKey) {
            Write-Host "API Key 不能为空，已取消。" -ForegroundColor Red
            exit 1
        }
    } else {
        Write-Host "本地服务商，无需 API Key。" -ForegroundColor Yellow
    }

    # ---- 写入 .env ----
    $map = @{}
    $map['VISION_PROVIDER'] = $provider
    if ($apiKey) { $map['VISION_API_KEY'] = $apiKey }
    if ($model)  { $map['VISION_MODEL'] = $model }
    if ($baseUrl){ $map['VISION_BASE_URL'] = $baseUrl }
    if ($provider -eq 'glm' -and $apiKey) { $map['GLM_API_KEY'] = $apiKey }   # 向后兼容
    Write-DotEnv $map
    Write-Host ""
    Write-Host "已保存到 .env" -ForegroundColor Green

    # ---- 第 5 步：测试连通 ----
    if ($p.NeedsKey -and $apiKey) {
        Write-Host ""
        Write-Host "正在测试接口连通性（可能需要几秒钟）..." -ForegroundColor Gray
        Write-Host ("  {0}" -f $baseUrl) -ForegroundColor Gray
        $res = Test-Endpoint $baseUrl $apiKey $model
        if ($res -eq 'OK') {
            Write-Host "  结果：连接正常 ✓" -ForegroundColor Green
        } else {
            Write-Host ("  结果：{0}" -f $res) -ForegroundColor Yellow
            Write-Host "  提示：即使此处失败，正式识别时仍可能可用（这是轻量检测）。" -ForegroundColor Gray
        }
    } else {
        Write-Host ""
        Write-Host "已选择本地服务商（无需 Key），启动对应服务后即可使用。" -ForegroundColor Green
    }
    Write-Host ""
    Write-Host "配置完成！接下来：双击 start-watcher.bat 启动监视器，然后截图并让 AI 识别。" -ForegroundColor Cyan
}

# =============================================================
# 入口
# =============================================================

# 删除配置
if ($RemoveKey) {
    if (Test-Path -LiteralPath $envFile) { Remove-Item -LiteralPath $envFile -Force }
    Write-Host ".env 已删除。" -ForegroundColor Yellow
    return
}

# 向后兼容：直接设 key（服务商固定智谱）
if ($SetKey) {
    $map = Read-DotEnv
    $map['VISION_PROVIDER'] = 'glm'
    $map['VISION_API_KEY']  = $SetKey
    if (-not $map['VISION_MODEL']) { $map['VISION_MODEL'] = $VisionProviders['glm'].Models[0] }
    $map['VISION_BASE_URL'] = $VisionProviders['glm'].BaseUrl
    $map['GLM_API_KEY']     = $SetKey
    Write-DotEnv $map
    Write-Host "GLM API Key 已保存到 .env（服务商：智谱）。" -ForegroundColor Green
    return
}

# 查看状态
if ($Status) {
    $cfg = Get-Config
    Write-Host ""
    Write-Host "======== 视觉桥 - 当前状态 ========" -ForegroundColor Cyan
    Write-Host ("- .env 文件存在:  {0}" -f (Test-Path -LiteralPath $envFile))
    Write-Host ("- 服务商:         {0}" -f $(if ($cfg.provider) { $cfg.provider } else { '(未配置)' }))
    if ($cfg.provider) { Write-Host ("- 模型:            {0}" -f $cfg.model) }
    if ($cfg.provider) { Write-Host ("- 接口地址:        {0}" -f $cfg.baseUrl) }
    if ($cfg.provider -eq 'ollama') {
        Write-Host "- API Key:        不需要（本地服务）"
    } else {
        Write-Host ("- API Key:        {0}" -f $(if ($cfg.apiKey) { '已设置' } else { '未设置' }))
    }
    Write-Host "- 系统:            $([Environment]::OSVersion.VersionString)"
    Write-Host ""
    if ($cfg.provider -and $cfg.baseUrl -and ($cfg.provider -eq 'ollama' -or $cfg.apiKey)) {
        Write-Host "正在测试接口连通性（轻量检测）..." -ForegroundColor Gray
        Write-Host ("  {0}" -f $cfg.baseUrl) -ForegroundColor Gray
        if ($cfg.provider -eq 'ollama') {
            $res = Test-Endpoint $cfg.baseUrl 'not-needed' $cfg.model
        } else {
            $res = Test-Endpoint $cfg.baseUrl $cfg.apiKey $cfg.model
        }
        if ($res -eq 'OK') { Write-Host "  结果：连接正常 ✓" -ForegroundColor Green }
        else { Write-Host ("  结果：{0}" -f $res) -ForegroundColor Yellow }
    }
    Write-Host ""
    if (-not $cfg.provider) {
        Write-Host "尚未配置。双击 setup.bat 完成配置。" -ForegroundColor Yellow
    }
    return
}

# 无参数 -> 进入交互式向导
Save-FromWizard
